### ISSUE TITLE
Hi, I've got some questiins about your activity, but your discord is not working, can u update it?

### ISSUE THREAD

**Issue by ellovich** [FahimFuad/Spike#5]

**Comment by FahimFuad** [comment]
@ellovich Sorry for the discord link being not working. I will update that.
Here is our server invite link `https://discord.gg/QugaNbUPzb`. Hope you join soon and tell us the questions 😄

**Comment by FahimFuad** [comment]
Closing this. You can contact us at the given discord server. 🙂
